apiVersion: v1
kind: Service
metadata:
  name: dealership-app-service
spec:
  selector:
    app: dealership-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30080