apiVersion: apps/v1
kind: Deployment
metadata:
  name: dealership-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dealership-app
  template:
    metadata:
      labels:
        app: dealership-app
    spec:
      containers:
      - name: dealership-app
        image: index.docker.io/vanestojanov/devops_project:d849e44f4da3afa529c235af2fc4aa4c5c528ece
        ports:
        - containerPort: 8000
        env:
        - name: MONGODB_HOST
          valueFrom:
            configMapKeyRef:
              name: mongodb
              key: MONGODB_HOST
        - name: MONGODB_PORT
          valueFrom:
            configMapKeyRef:
              name: mongodb
              key: MONGODB_PORT
        - name: MONGODB_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-credentials
              key: MONGODB_USERNAME
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-credentials
              key: MONGODB_PASSWORD
