name: Deploy to Development

on:
  pull_request:
    branches:
      - Development
    types:
      - closed

jobs:
  deploy-to-development:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Deployment
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'dealership-app-devops'
          publish-profile: "${{secrets.AZURE_PUBLISH_PROFILE}}"
          images: 'vanestojanov/devops_project:latest'
