# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Pre-commit, Build and deploy container app to Azure Web App - dealership-app-devops

on:
  push:
    branches:
      - Development
  workflow_dispatch:

jobs:
  pre-commit-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit on all files
        run: pre-commit run --all-files
  build:
    runs-on: 'ubuntu-latest'
    needs: pre-commit-check
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_d4c28e57b72f4b4491d25755417adebd }}
        password: ${{ secrets.AzureAppService_ContainerPassword_2acc72c1c3604d2a9b854e4b5f7b99e0 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_d4c28e57b72f4b4491d25755417adebd }}/devops_project:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'dealership-app-devops'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_2a0cc3bdf87c4a3cb24e8f5872c861a4 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_d4c28e57b72f4b4491d25755417adebd }}/devops_project:${{ github.sha }}'